ConnectedIn 23-02/connectedin/urls.py
from django.contrib import admin
from django.urls import path
from perfis import views
from usuarios.views import RegistrarUsuarioView
from django.contrib.auth import views as V
from timeline import views as VT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('perfil/<int:perfil_id>', views.exibir_perfil, name='exibir'),
    path('perfil/<int:perfil_id>/convidar', views.convidar, name='convidar'),
    path('convite/<int:convite_id>/aceitar', views.aceitar, name='aceitar'),
    path('convite/<int:convite_id>/recusar', views.recusar, name='recusar'),
    path('perfil/<int:perfil_id>/desfazer', views.desfazer, name='desfazer'),
    path('registrar/', RegistrarUsuarioView.as_view(), name="registrar"),
    path('login/', V.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('logout/', V.LogoutView.as_view(template_name='login.html'), name="logout"),
    path('timeline/<int:post_id>', VT.excluir_post, name='excluir'),
]

ConnectedIn 23-02/perfis/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Perfil(models.Model):
    nome = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=15, null=False)
    nome_empresa = models.CharField(max_length=255, null=False)
    contatos = models.ManyToManyField('Perfil')
    usuario = models.OneToOneField(User, related_name='perfil', on_delete=models.CASCADE)

    @property
    def email(self):
        return self.usuario.email

    def desfazer(self, perfil):
        self.contatos.remove(perfil)
        perfil.contatos.remove(self)

    def pode_convidar(self, perfil):
        nao_pode = self.convite_a_si_mesmo(perfil) or self.ja_eh_contato(perfil) or self.ja_possui_convite(perfil)

        return not nao_pode

    def convite_a_si_mesmo(self, perfil):
        return self == perfil

    def ja_eh_contato(self, perfil):
        return self.contatos.filter(id=perfil.id).exists()

    def ja_possui_convite(self, perfil):
        return (Convite.objects.filter(solicitante=self, convidado=perfil).exists() or
                Convite.objects.filter(solicitante=perfil, convidado=self).exists())

    def convidar(self, perfil_convidado):
        if (self.pode_convidar(perfil_convidado)):
            convite = Convite(solicitante=self, convidado=perfil_convidado)
            convite.save()

    def __str__(self):
        return self.nome


class Convite(models.Model):
    solicitante = models.ForeignKey(Perfil, on_delete=models.CASCADE,
                                    related_name='convites_feitos')
    convidado = models.ForeignKey(Perfil, on_delete=models.CASCADE,
                                  related_name='convites_recebidos')

    def aceitar(self):
        self.solicitante.contatos.add(self.convidado)
        self.convidado.contatos.add(self.solicitante)
        self.delete()

    def recusar(self):
        self.delete()

ConnectedIn 23-02/timeline/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    usuario = models.ForeignKey(User, related_name='Post', on_delete= models.CASCADE)
    text = models.CharField(max_length=255)
    date_post = models.DateField()

class Timeline(models.Model):
    posts = models.ForeignKey("Post", related_name='post_da_timeline', on_delete=models.CASCADE)

ConnectedIn 23-02/usuarios/models.py
from django.db import models

# Create your models here.

ConnectedIn 23-02/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')

        user_exists = User.objects.filter(username=self.cleaned_data['nome']).exists()
        if user_exists:
            self.adiciona_erro('Usuário já existente.')
            valid = False

        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(forms.forms.NON_FIELD_ERRORS,
                                         forms.utils.ErrorList())
        errors.append(message)

ConnectedIn 23-02/perfis/views.py
from django.shortcuts import render
from perfis.models import Perfil, Convite
from django.shortcuts import redirect
from django.contrib.auth.decorators import *

# Create your views here.
@login_required
def index(request):
    return render(request, 'index.html', {'perfis': Perfil.objects.all(),
                                          'perfil_logado': get_perfil_logado(request)})

@login_required
def exibir_perfil(request, perfil_id):
    # perfil = get(perfil_id)
    perfil = Perfil.objects.get(id=perfil_id)

    return render(request, 'perfil.html',
                  {'perfil': perfil,
                   'perfil_logado': get_perfil_logado(request)})


def get(perfil_id):
    if (perfil_id == 1):
        return Perfil('Ely', 'ely@ifpi.edu.br',
                      '99999-9999', 'ifpi')
    if (perfil_id == 2):
        return Perfil('Pedro', 'pedro@gmail.com',
                      '99999-8888', 'Google')
    if (perfil_id == 3):
        return Perfil('Maria', 'maria@hotmail.com',
                      '88888-7777', 'MS')

@login_required
def convidar(request, perfil_id):
    perfil_a_convidar = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)

    if (perfil_logado.pode_convidar(perfil_a_convidar)):
        perfil_logado.convidar(perfil_a_convidar)

    return redirect('index')

@login_required
def get_perfil_logado(request):
    return request.user.perfil

@login_required
def aceitar(request, convite_id):
    convite = Convite.objects.get(id=convite_id)
    convite.aceitar()
    return redirect('index')

@login_required
def recusar(request, convite_id):
    convite = Convite.objects.get(id=convite_id)
    convite.recusar()
    return redirect('index')

@login_required
def desfazer(request, perfil_id):
    perfil = Perfil.objects.get(id=perfil_id)
    perfil.desfazer(get_perfil_logado(request))
    return redirect('index')

ConnectedIn 23-02/timeline/views.py
from django.shortcuts import *
from perfis.models import Perfil
# Create your views here.
from timeline.models import Post


def carregar_posts(request, id_perfil):
    perfil = Perfil.objects.get(id_perfil)
    posts = Post.objects.filter(usuario=perfil.user)
    posts_contatos = get_post_contatos(perfil.contatos)
    return render('timeline.html',
                  {'my_posts': posts,
                   'posts_contatos': posts_contatos})


def get_post_contatos(contatos):
    posts = []
    for contato in contatos:
        posts.append(Post.objects.filter(usuario=contato))
    return posts


def excluir_post(request, post_id):
    Post.objects.filter(id=post_id).delete()
    return redirect('self')

ConnectedIn 23-02/usuarios/views.py
from django.shortcuts import *
from django.contrib.auth.models import User
from django.views.generic.base import View
from perfis.models import Perfil
from usuarios.forms import RegistrarUsuarioForm


class RegistrarUsuarioView(View):
    template_name = 'registrar.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        form = RegistrarUsuarioForm(request.POST)

        if form.is_valid():
            dados_form = form.cleaned_data
            usuario = User.objects.create(username=dados_form['nome'],
                                          email=dados_form['email'],
                                          password=dados_form['senha'])
            perfil = Perfil(nome=dados_form['nome'],
                            telefone=dados_form['telefone'],
                            nome_empresa=dados_form['nome_empresa'],
                            usuario=usuario)
            perfil.save()
            return redirect('index')
        return render(request, self.template_name, {'form': form})

ConnectedIn 23-02/perfis/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang = "pt-br">
	<head>
		<meta charset="utf-8">
		<title>ConnectedIn</title>
		<link rel="stylesheet" 
			 href="{% static 'styles/bootstrap.css' %}">
		<link rel="stylesheet" 
			 href="{% static 'styles/main.css' %}">

	</head>
	<body>
		<div class="container">
			<div class = "header">
				<ul class = "nav nav-pills pull-right">
					<li><a href = "{% url 'index' %}">{{ perfil_logado.nome }}</a></li>
					<li><a href = "/logout/">Logout</a></li>
				</ul>
				<h3 class = "text-muted">ConnectedIn</h3>
			</div>
			
			<div class="row content">
				{% block body%}
				{% endblock %}				
			</div>		
		</div>	
	</body>
</html>

ConnectedIn 23-02/perfis/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="col-lg-12"> 		
	<div class="panel panel-default">
		<div class="panel-heading">
			<strong>Todos os perfis</strong>
		</div>
		{% if perfis %}
		<ul class="list-group">
			{% for perfil in perfis %}
				<li class="list-group-item">
					<a href = "{% url 'exibir' perfil.id %}">	{{ perfil.nome }} / {{ perfil.email }}
					</a>	
				</li>
			{% endfor %}
		{% else %}	
			<p>Não há perfis cadastrados</p>
		{% endif %}
		</ul>
	</div>	

    <div class="panel panel-default">
        {% with total=perfil_logado.contatos.count %}
            {% if total %}
                <div class="panel-heading">
                    <strong> {{ total }}  
                        Contato{{ total|pluralize }}
                    </strong>
                </div>
                <ul class="list-group">
                    {% for perfil in perfil_logado.contatos.all %}
                        <li class = "list-group-item">
                            <a href = "{% url 'exibir' perfil.id %}">
                                {{ perfil }}
                            </a>
                            <a class="pull-right" href="{% url 'desfazer' perfil.id %}">
                                desfazer amizade
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="panel-body">
                    Não há contatos :(
                </div>    
            {% endif %}
        {% endwith %}    
    </div>    

    <div class="panel panel-default">
        {% with total=perfil_logado.convites_recebidos.count %}

            {% if total %}
                <div class="panel-heading">
                    <strong> {{ total }}  
                    Convite{{ total|pluralize }} aguardando aprovação</strong>
                </div>
                <ul class="list-group">
                    {% for convite in perfil_logado.convites_recebidos.all %}
                        <li class = "list-group-item">
                           <ul class = "list-inline">
                                <li class = "list-inline-item">
                                    <a href = "{% url 'exibir' convite.solicitante.id %}">
                                        {{convite.solicitante.nome}}
                                    </a>
                                </li>
                                <li class = "list-inline-item pull-right">
                                    <a href = "{% url 'recusar' convite.id %}">recusar</a>
                                </li>
                                <li class = "list-inline-item pull-right">
                                    <a href = "{% url 'aceitar' convite.id %}">aceitar</a>
                                </li>
                        
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <div class="panel-body">
                    Não há convites
                </div>    
            {% endif %}
        {% endwith %}    
    </div>    
</div>
{% endblock %}

ConnectedIn 23-02/perfis/templates/perfil.html
{% extends 'base.html' %}
{% block body %}
<div class = "col-lg-12">
		<h2 style="margin-top: 0px">{{ perfil.nome }}</h2>
		<address>			
			<a href = "mailto:{{ perfil.email }}">{{ perfil.email }}</a>
			<br>
			<strong>{{ perfil.nome_empresa }}</strong>
		
		</address>

		{% if perfil_logado.pode_convidar %}
			<div class = "well well-sm">Vocês já estão conectados</div>
		{% elif perfil != perfil_logado %}	
			<a href = "{% url 'convidar' perfil.id %}">
				Convidar
			</a>	
		{% endif %}	
</div>		
{% endblock %}		

ConnectedIn 23-02/timeline/templates/timeline.html
{% extends 'base.html' %}
{% block body %}
<div class="col-lg-12">

    <div class="panel panel-default">
        <ul class="list-group">
            {% for post in my_posts %}
                <li class = "list-group-item">
                    <p>{{post.text}}</p>
                    <p>{{post.date_post}}</p>
                    <a class="pull-right" href="{% url 'excluir_post' post.id %}">
                    </a>
                </li>
            {% endfor %}

            {% for posts in posts_contatos%}
                {% for post in posts %}
                    <li><p>{{post.name}}</p></li>
                    <li><p>{{post.date_post}}</p></li>
                {% end for%}
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

ConnectedIn 23-02/usuarios/templates/base_usuario.html
<!-- connectedin/usuarios/templates/base_usuario.html -->
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>ConnectedIn</title>
        <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "styles/signin.css" %}" rel="stylesheet">
    </head>
    <body>
        <div class="container">
        {% block body %}
        {% endblock %}
        </div>
    </body>
</html>

ConnectedIn 23-02/usuarios/templates/login.html
{% extends "base_usuario.html" %}

{% block body %}
	
	<form class="form-signin" role="form" action="{% url 'login' %}" method="post">
		{% csrf_token %}
		<h2 class="form-signin-heading">Login</h2>
		<input id="id_username" name="username" class="form-control" placeholder="Nome" required autofocus>
		<input type="password" id="id_password" name="password" class="form-control" placeholder="Senha" required>
		<button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>
		{% if form.errors %}
			<div class="alert alert-danger">
				<button type="button" class="close"
				data-dismiss="alert" aria-hidden="true">×</button>
				Por favor, verifique o Email e/ou Senha informados
			</div>
		{% endif %}
		<a href="{% url 'registrar' %}">registre-se</a>
	</form>

{% endblock %}

ConnectedIn 23-02/usuarios/templates/registrar.html
<!-- connectedin/usuarios/templates/registrar.html -->
{% extends "base_usuario.html" %}
{% block body %}
    <form action="{% url 'registrar' %}"

method="post">
{% csrf_token %}
<h2 >Crie seu usuário</h2>
<input id="id_email" name="email" placeholder="Email *" required autofocus>
<input id="id_nome" name="nome" placeholder="Nome *" required >
<input type="password" id="id_senha" name="senha"

placeholder="Senha *" required>

<hr />
<input id="id_telefone" name="telefone" placeholder="Telefone" required>
<input id="id_nome_empresa" name="nome_empresa" placeholder="Empresa"

required>

<hr />
<button type="submit" value="Login">Registrar</button>
</form>
{% endblock %}